# Generated by Django 5.1.7 on 2025-07-15 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_image_avatar_employer_image_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image_avatar',
            field=models.ImageField(blank=True, default='avatars/user-default.png', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='image_avatar',
            field=models.ImageField(blank=True, default='avatars/user-default.png', null=True, upload_to='avatars/'),
        ),
    ]
