# Generated by Django 5.1.7 on 2025-07-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_programminglanguage_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='languages',
            field=models.ManyToManyField(blank=True, to='users.programminglanguage'),
        ),
    ]
