# Generated by Django 5.1.7 on 2025-07-15 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
    ]
