# Generated by Django 5.1.7 on 2025-07-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_programminglanguage_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='languages',
        ),
    ]
