# Generated by Django 5.1.7 on 2025-07-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_employee_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programminglanguage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='programminglanguage',
            name='owner',
        ),
        migrations.AddField(
            model_name='employee',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, null=True, to='users.programminglanguage'),
        ),
    ]
