# Generated by Django 5.1.7 on 2025-07-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_programminglanguage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
